package org.example;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

public class Inventory {

    // this is a bit confusing so I'll explain

    // first we grab the png file from the resources directory
    static ImageIcon product1Icon = new ImageIcon(
            //Objects.requireNonNull is autogenerated by intelliJ lol
            Objects.requireNonNull(Inventory.class.getResource("/assets/ip10-white.png"))
    );
    static ImageIcon product2Icon = new ImageIcon(
            Objects.requireNonNull(Inventory.class.getResource("/assets/ip11-green.png"))
    );
    static ImageIcon product3Icon = new ImageIcon(
            Objects.requireNonNull(Inventory.class.getResource("/assets/ip13-pink.png"))
    );
    static ImageIcon product4Icon = new ImageIcon(
            Objects.requireNonNull(Inventory.class.getResource("/assets/ip14-blue.png"))
    );
    static ImageIcon product5Icon = new ImageIcon(
            Objects.requireNonNull(Inventory.class.getResource("/assets/ip15-blue.png"))
    );
    static ImageIcon product6Icon = new ImageIcon(
            Objects.requireNonNull(Inventory.class.getResource("/assets/ip16-pink.png"))
    );
    static ImageIcon product7Icon = new ImageIcon(
            Objects.requireNonNull(Inventory.class.getResource("/assets/ip17-orange.png"))
    );
    static ImageIcon product8Icon = new ImageIcon(
            Objects.requireNonNull(Inventory.class.getResource("/assets/iphone-12-mini-blue.png"))
    );

    // we then resize them
    static Image scaledProduct1Icon = product1Icon.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH);
    static Image scaledProduct2Icon = product2Icon.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH);
    static Image scaledProduct3Icon = product3Icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    static Image scaledProduct4Icon = product4Icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    static Image scaledProduct5Icon = product5Icon.getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH);
    static Image scaledProduct6Icon = product6Icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    static Image scaledProduct7Icon = product7Icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    static Image scaledProduct8Icon = product8Icon.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH);

    // this is a bit weird because we then (kind of?) converted the Image object to an
    // ImageIcon object because JLabels for some reason does not accept a raw Image type object,
    // but it accepts an ImageIcon type object, so we did this by passing the raw Image type object
    // to a ImageIcon constructor which should then return an ImageIcon object that contains the
    // raw Image lol, weird behaviour indeed.
    static ImageIcon newProduct1Icon = new ImageIcon(scaledProduct1Icon);
    static ImageIcon newProduct2Icon = new ImageIcon(scaledProduct2Icon);
    static ImageIcon newProduct3Icon = new ImageIcon(scaledProduct3Icon);
    static ImageIcon newProduct4Icon = new ImageIcon(scaledProduct4Icon);
    static ImageIcon newProduct5Icon = new ImageIcon(scaledProduct5Icon);
    static ImageIcon newProduct6Icon = new ImageIcon(scaledProduct6Icon);
    static ImageIcon newProduct7Icon = new ImageIcon(scaledProduct7Icon);
    static ImageIcon newProduct8Icon = new ImageIcon(scaledProduct8Icon);

    // and then we define the actual product object itself
    final static private Product product1 = new Product("iPhone 10 White", 99.99, newProduct1Icon);
    final static private Product product2 = new Product("iPhone 11 Green", 199.99, newProduct2Icon);
    final static private Product product3 = new Product("iPhone 13 Pink", 299.99, newProduct3Icon);
    final static private Product product4 = new Product("iPhone 14 Blue", 399.99, newProduct4Icon);
    final static private Product product5 = new Product("iPhone 15 Blue", 499.99, newProduct5Icon);
    final static private Product product6 = new Product("iPhone 16 Pink", 599.99, newProduct6Icon);
    final static private Product product7 = new Product("iPhone 17 Orange", 699.99, newProduct7Icon);
    final static private Product product8 = new Product("iPhone 12 Mini Blue", 799.99, newProduct8Icon);

    // we use this to iterate through the stuff products
    static private final Product[] inventory = {
            product1, product2, product3,
            product4, product5, product6,
            product7, product8
    };

    public Product[] getInventory() {
        return inventory;
    }
}
